language: python

cache: pip

matrix:
  fast_finish: true
  include:
    - os: linux
      env: PYTHON_VERSION="3.4" PYTHON_ARCH="32"
    - os: linux
      env: PYTHON_VERSION="3.4" PYTHON_ARCH="64"
    - os: linux
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="32"
    - os: linux
      env: PYTHON_VERSION="3.5" PYTHON_ARCH="64"
    - os: linux
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="32"
    - os: linux
      env: PYTHON_VERSION="3.6" PYTHON_ARCH="64"


install:
  - python -c "import platform; print(platform.architecture())"
  - python install.py 
  - $DENV
  - pip install coverage
  - pip install coveralls

script:
  - export PYTHONWARNINGS=all
  - python manage.py check
  - python manage.py test 
  - coverage run --omit="*/migrations*" --source="." manage.py test

after_success:
  coveralls
