# Generated by Django 2.0.2 on 2018-03-07 14:12

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Filesystem',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_path', models.TextField()),
                ('source_type',
                 models.CharField(
                     choices=[('file', 'Source is a file'),
                              ('dir', 'Source is a directory')],
                     default='file',
                     max_length=4)),
                ('destination_path', models.TextField()),
                ('destination_type',
                 models.CharField(
                     choices=[('file', 'Replace with'), ('dir',
                                                         'Insert into')],
                     default='file',
                     max_length=4)),
                ('hash_value',
                 models.CharField(blank=True, default='', max_length=32)),
                ('command_uuid',
                 models.CharField(
                     blank=True, max_length=32, null=True, unique=True)),
                ('error_code',
                 models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('path', models.TextField()),
                ('arguments',
                 models.TextField(
                     blank=True,
                     validators=[frontend.models.validate_argument_list])),
                ('start_time', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('last_ran', models.BooleanField(default=False)),
                ('is_initialized', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('error_code',
                 models.CharField(blank=True, default='', max_length=1000)),
                ('current_index', models.IntegerField(blank=True, default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGraphFiles',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('index', models.IntegerField()),
                ('filesystem',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='frontend.Filesystem')),
                ('script',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='frontend.Script')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGraphPrograms',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address',
                 models.CharField(
                     max_length=17,
                     unique=True,
                     validators=[frontend.models.validate_mac_address])),
                ('command_uuid',
                 models.CharField(
                     blank=True, max_length=32, null=True, unique=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStatus',
            fields=[
                ('program',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     primary_key=True,
                     serialize=False,
                     to='frontend.Program')),
                ('code', models.CharField(blank=True, max_length=200)),
                ('command_uuid', models.CharField(max_length=32, unique=True)),
                ('running', models.BooleanField(default=True)),
                ('timeouted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='scriptgraphprograms',
            name='program',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Program'),
        ),
        migrations.AddField(
            model_name='scriptgraphprograms',
            name='script',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Script'),
        ),
        migrations.AddField(
            model_name='program',
            name='slave',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Slave'),
        ),
        migrations.AddField(
            model_name='filesystem',
            name='slave',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Slave'),
        ),
        migrations.AlterUniqueTogether(
            name='scriptgraphprograms',
            unique_together={('script', 'index', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='scriptgraphfiles',
            unique_together={('script', 'index', 'filesystem')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'slave')},
        ),
        migrations.AlterUniqueTogether(
            name='filesystem',
            unique_together={('source_path', 'destination_path', 'slave',
                              'source_type', 'destination_type'), ('name',
                                                                   'slave')},
        ),
    ]
