# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('arguments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[frontend.models.validate_mac_address])),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Slave'),
        ),
    ]
