# Generated by Django 2.0.1 on 2018-01-17 13:40

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sourcePath', models.CharField(max_length=200)),
                ('destinationPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('arguments', models.CharField(blank=True, max_length=200)),
                ('start_time', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'INIT'), (1, 'WAITING_FOR_SLAVES'), (2, 'NEXT_STEP'), (3, 'WAITING_FOR_PROGRAMS'), (4, 'SUCCESS'), (5, 'ERROR')], default=0)),
                ('index', models.IntegerField(default=-1)),
                ('error_code', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGraphFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.File')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Script')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGraphPrograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[frontend.models.validate_mac_address])),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStatus',
            fields=[
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.Program')),
                ('code', models.CharField(blank=True, max_length=200)),
                ('command_uuid', models.CharField(max_length=32, unique=True)),
                ('running', models.BooleanField(default=True)),
                ('timeouted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlaveStatus',
            fields=[
                ('slave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.Slave')),
                ('command_uuid', models.CharField(max_length=32, unique=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='scriptgraphprograms',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Program'),
        ),
        migrations.AddField(
            model_name='scriptgraphprograms',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Script'),
        ),
        migrations.AddField(
            model_name='schedulerstatus',
            name='script',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frontend.Script'),
        ),
        migrations.AddField(
            model_name='program',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Slave'),
        ),
        migrations.AddField(
            model_name='file',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Slave'),
        ),
        migrations.AlterUniqueTogether(
            name='scriptgraphprograms',
            unique_together={('script', 'index', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='scriptgraphfiles',
            unique_together={('script', 'index', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'slave')},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'slave')},
        ),
    ]
