# Generated by Django 2.0.1 on 2018-01-18 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulerstatus',
            name='script',
        ),
        migrations.DeleteModel(
            name='SchedulerStatus',
        ),
    ]
