# Generated by Django 2.0.1 on 2018-01-09 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sourcePath', models.CharField(max_length=200)),
                ('destinationPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramStatus',
            fields=[
                ('program',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     primary_key=True,
                     serialize=False,
                     to='frontend.Program')),
                ('code', models.CharField(blank=True, max_length=200)),
                ('command_uuid', models.CharField(max_length=32, unique=True)),
                ('running', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGraphFiles',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('index', models.IntegerField()),
                ('file',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='frontend.File')),
                ('script',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='frontend.Script')),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGraphPrograms',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SlaveStatus',
            fields=[
                ('slave',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     primary_key=True,
                     serialize=False,
                     to='frontend.Slave')),
                ('command_uuid', models.CharField(max_length=32, unique=True)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='arguments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('name', 'slave')},
        ),
        migrations.AddField(
            model_name='scriptgraphprograms',
            name='program',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Program'),
        ),
        migrations.AddField(
            model_name='scriptgraphprograms',
            name='script',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Script'),
        ),
        migrations.AddField(
            model_name='file',
            name='slave',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Slave'),
        ),
        migrations.AlterUniqueTogether(
            name='scriptgraphprograms',
            unique_together={('script', 'index', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='scriptgraphfiles',
            unique_together={('script', 'index', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'slave')},
        ),
    ]
