# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('command', models.CharField(max_length=200)),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Slave')),
            ],
        ),
    ]
