# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='arguments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('name', 'slave')]),
        ),
    ]
