# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStatus',
            fields=[
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.Program')),
                ('error', models.CharField(max_length=200)),
                ('started', models.DateTimeField()),
                ('stopped', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlaveStatus',
            fields=[
                ('slave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.Slave')),
                ('boottime', models.DateTimeField()),
                ('reply_channel', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='arguments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('name', 'slave')]),
        ),
    ]
