# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20171212_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.Program')),
                ('error', models.CharField(max_length=200)),
                ('started', models.DateTimeField()),
                ('stopped', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SlaveOnline',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.Slave')),
                ('booted', models.DateTimeField()),
                ('online', models.BooleanField()),
            ],
        ),
    ]
