# Generated by Django 2.0.1 on 2018-01-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180108_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='running',
        ),
        migrations.AddField(
            model_name='programstatus',
            name='running',
            field=models.BooleanField(default=True),
        ),
    ]
