# Generated by Django 2.0.1 on 2018-01-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180109_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='start_time',
            field=models.IntegerField(default=-1),
        ),
    ]
