# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20171212_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sourcePath', models.CharField(max_length=200)),
                ('destinationPath', models.CharField(max_length=200)),
                ('slave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Slave')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('name', 'slave')]),
        ),
    ]
