# Generated by Django 2.0.1 on 2018-01-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180109_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerStatus',
            fields=[
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='frontend.Script')),
                ('index', models.IntegerField(default=-1)),
                ('wait', models.BooleanField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='programstatus',
            name='timeouted',
            field=models.BooleanField(default=False),
        ),
    ]
