# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20171217_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slavestatus',
            name='reply_channel',
        ),
        migrations.AlterField(
            model_name='programstatus',
            name='stopped',
            field=models.DateTimeField(blank=True),
        ),
    ]
