# Generated by Django 2.0.1 on 2018-01-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180118_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='error_code',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='script',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='last_ran',
            field=models.BooleanField(default=False),
        ),
    ]
