# Generated by Django 2.0.1 on 2018-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180119_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='current_index',
            field=models.IntegerField(default=-1),
        ),
    ]
