# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20171217_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programstatus',
            old_name='error',
            new_name='code',
        ),
    ]
