# Generated by Django 2.0.1 on 2018-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_program_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstatus',
            name='timeouted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='current_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='script',
            name='error_code',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='script',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='last_ran',
            field=models.BooleanField(default=False),
        ),
    ]
