# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20171129_1708'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([]),
        ),
    ]
