# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20171128_1448'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('name', 'slave')]),
        ),
    ]
