# Generated by Django 2.0.1 on 2018-01-16 13:38

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_program_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='arguments',
            field=models.CharField(
                blank=True,
                max_length=1000,
                validators=[frontend.models.validate_argument_list]),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='program',
            name='path',
            field=models.CharField(max_length=1000),
        ),
    ]
