# Generated by Django 2.0.1 on 2018-01-21 22:51
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_programstatus_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstatus',
            name='dummy',
        ),
    ]
