# Generated by Django 2.0.1 on 2018-01-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180116_1406'),
        ('frontend', '0003_program_start_time'),
    ]

    operations = [
    ]
