# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20171217_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstatus',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
