# Generated by Django 2.0.1 on 2018-01-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_programstatus_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='slavestatus',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
