# Generated by Django 2.0.1 on 2018-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20180121_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slave',
            name='command_uuid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
