# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20171217_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programstatus',
            name='stopped',
            field=models.DateTimeField(null=True),
        ),
    ]
