# Generated by Django 2.0.1 on 2018-01-22 19:34

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_slavestatus_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='arguments',
            field=models.TextField(blank=True, validators=[frontend.models.validate_argument_list]),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='program',
            name='path',
            field=models.TextField(),
        ),
    ]
