# Generated by Django 2.0.1 on 2018-01-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20180121_1333'),
        ('frontend', '0004_auto_20180116_1338'),
    ]

    operations = [
    ]
