# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20171217_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sourcePath', models.CharField(max_length=200)),
                ('destinationPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='file',
            name='slave',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Slave'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('name', 'slave')]),
        ),
    ]
