# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20171217_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slave',
            name='id',
            field=models.AutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID'),
        ),
    ]
