# Generated by Django 2.0.1 on 2018-01-22 09:11

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_remove_slavestatus_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slavestatus',
            name='slave',
        ),
        migrations.AddField(
            model_name='programstatus',
            name='timeouted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='current_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='script',
            name='error_code',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='script',
            name='is_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='script',
            name='last_ran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slave',
            name='command_uuid',
            field=models.CharField(
                blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='slave',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='arguments',
            field=models.TextField(
                blank=True,
                validators=[frontend.models.validate_argument_list]),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='program',
            name='path',
            field=models.TextField(),
        ),
        migrations.DeleteModel(name='SlaveStatus', ),
    ]
