# Generated by Django 2.0.1 on 2018-01-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20180122_0911'),
        ('frontend', '0007_auto_20180122_1934'),
    ]

    operations = []
