# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20180104_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('payload', models.TextField()),
                ('slave',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='frontend.Slave')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='script',
            unique_together=set([('name', 'slave')]),
        ),
    ]
