# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-04 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20180104_1725'),
        ('frontend', '0007_auto_20180104_1442'),
    ]

    operations = [
    ]
