# Generated by Django 2.0.1 on 2018-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20180125_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'slave'), ('destination_path', 'source_path'), ('destination_path', 'hash_value')},
        ),
    ]
