# Generated by Django 2.0.1 on 2018-01-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20180127_1652'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'slave'),
                             ('source_path', 'destination_path', 'hash_value',
                              'slave')},
        ),
    ]
