# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20180106_0801'),
        ('frontend', '0008_merge_20180104_1727'),
    ]

    operations = [
    ]
