# Generated by Django 2.0.1 on 2018-01-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20180127_1657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('name', 'slave'), ('source_path',
                                                 'destination_path', 'slave')},
        ),
    ]
