# Generated by Django 2.0.1 on 2018-01-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20180122_1934'),
        ('frontend', '0011_auto_20180127_1703'),
    ]

    operations = []
