# Generated by Django 2.0.1 on 2018-01-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_merge_20180129_1511'),
        ('frontend', '0008_merge_20180125_1602'),
    ]

    operations = [
    ]
