# Generated by Django 2.0.1 on 2018-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_merge_20180129_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
