# Generated by Django 2.0.2 on 2018-02-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20180217_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scriptgraphfiles',
            old_name='file',
            new_name='filesystem',
        ),
        migrations.AlterUniqueTogether(
            name='scriptgraphfiles',
            unique_together={('script', 'index', 'filesystem')},
        ),
    ]
