# Generated by Django 2.0.2 on 2018-03-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20180218_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='destination_type',
            field=models.CharField(choices=[('file', 'Replace with'), ('dir', 'Insert into')], default='file', max_length=4),
        ),
        migrations.AlterField(
            model_name='filesystem',
            name='source_type',
            field=models.CharField(choices=[('file', 'Replace with'), ('dir', 'Insert into')], default='file', max_length=4),
        ),
        migrations.AlterField(
            model_name='script',
            name='current_index',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='script',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
