# Generated by Django 2.0.2 on 2018-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20180302_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='source_type',
            field=models.CharField(choices=[('file', 'Source is a file'), ('dir', 'Source is a directory')], default='file', max_length=4),
        ),
    ]
